In [ ]:
import tensorflow as tf
print(tf.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import mae
from tensorflow.keras.optimizers import SGD,Adam


2.12.0


In [ ]:
#creating tensors with tf.constant()
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
scalar.numpy()    

4

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,1])
print(vector.ndim)
print(vector.numpy())
print(vector.dtype)

2
[[10  1]]
<dtype: 'int32'>


In [ ]:
matrix = tf.constant([[10,1],[1,3]])
print(matrix.ndim)
print(matrix.numpy())
print(matrix.dtype)

2
[[10  1]
 [ 1  3]]
<dtype: 'int32'>


In [ ]:
tensor = tf.constant([[[1,2,3],
                       [2,2,1]],
                      [[2,3,4],
                       [4,5,6]],
                      [[1,2,4],
                       [5,6,7]],
                       [[9,9,9],
                      [1,1,1]]])
tensor.ndim

3

In [ ]:
tensor.shape

TensorShape([4, 2, 3])

#Variable

<li>Variable can be changes using assign
<li>Constant cannot be changes

In [ ]:
variable_var = tf.Variable([10,1])
constant_var = tf.constant([10,1])



In [ ]:
variable_var[0] = 11

TypeError: ignored

In [ ]:
variable_var[0].assign(11)
print(variable_var) 

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  1], dtype=int32)>


In [ ]:
constant_var[0] = 11

TypeError: ignored

#Creating random Tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42)


In [ ]:
random_1.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.random.normal(shape=(2,2),seed=22)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.1020602 ,  1.135856  ],
       [-0.07225064,  0.35086146]], dtype=float32)>

In [ ]:
tf.random.set_seed(22)
tf.random.normal(shape=(2,2),seed=12)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.3913167 ,  0.27398315],
       [-0.46710163, -0.47542152]], dtype=float32)>

In [ ]:
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=5)
     

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [ ]:
import numpy as np
a = tf.constant(np.random.randint(low=0,high = 100,size=50))
a.shape
a.ndim
tf.size(a)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [ ]:
tf.reshape(a,shape=(5,10))

<tf.Tensor: shape=(5, 10), dtype=int64, numpy=
array([[83, 98, 14, 45, 90, 76, 33, 47, 18, 84],
       [69, 12, 45, 11, 59, 35, 65, 73,  6, 94],
       [51, 67, 85, 42, 84, 70, 39, 90, 58,  3],
       [81, 31, 54,  7, 36, 12, 43, 93,  3,  1],
       [93, 52, 41,  8, 91, 49, 10, 64, 91, 41]])>

In [ ]:
print(tf.reduce_min(a))
print(tf.reduce_max(a))
print(tf.reduce_mean(a))
print(tf.reduce_sum(a))

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(98, shape=(), dtype=int64)
tf.Tensor(50, shape=(), dtype=int64)
tf.Tensor(2547, shape=(), dtype=int64)


In [ ]:
tf.cast(a,dtype=float)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([83., 98., 14., 45., 90., 76., 33., 47., 18., 84., 69., 12., 45.,
       11., 59., 35., 65., 73.,  6., 94., 51., 67., 85., 42., 84., 70.,
       39., 90., 58.,  3., 81., 31., 54.,  7., 36., 12., 43., 93.,  3.,
        1., 93., 52., 41.,  8., 91., 49., 10., 64., 91., 41.],
      dtype=float32)>

#tf(array) convert ndarray to tensorflow
#tensor.numpy()  convert tensor to numpy

#Finding access to GPU's

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Thu May  4 20:03:11 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#Linear Regression

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot

In [ ]:
x = tf.constant([2,4,6,8,10,10,15],dtype=float)
y = tf.constant([10,20,30,40,50,50,44],dtype=float)

In [ ]:
x.shape,y.shape

(TensorShape([7]), TensorShape([7]))

In [ ]:

model =  Sequential()
model.add(Dense(1,input_shape = (7,)))
model.compile(loss = mae,optimizer = SGD() , metrics =['mae'])
model.fit(x,y,epochs= 5)

Epoch 1/5


ValueError: ignored

In [ ]:
tf.random.set_seed(42)
x_2 = tf.expand_dims(x,1)
model =  Sequential()
model.add(Dense(1))
model.compile(loss = mae,optimizer = SGD() , metrics =['mae'])
model.fit(x_2,y,epochs= 5)

Epoch 1/5
1/1 [==============================] - 0s 361ms/step - loss: 34.9162 - mae: 34.9162
Epoch 2/5
1/1 [==============================] - 0s 11ms/step - loss: 34.2889 - mae: 34.2889
Epoch 3/5
1/1 [==============================] - 0s 10ms/step - loss: 33.6616 - mae: 33.6616
Epoch 4/5
1/1 [==============================] - 0s 10ms/step - loss: 33.0342 - mae: 33.0342
Epoch 5/5
1/1 [==============================] - 0s 11ms/step - loss: 32.4069 - mae: 32.4069


In [ ]:
x_2

<tf.Tensor: shape=(7, 1), dtype=float32, numpy=
array([[ 2.],
       [ 4.],
       [ 6.],
       [ 8.],
       [10.],
       [10.],
       [15.]], dtype=float32)>

#Improve model

In [ ]:
model2 = Sequential()
model2.add(Dense(100,activation = 'relu',input_shape=(7,)))
model2.add(Dense(100,activation = 'relu'))
model2.add(Dense(1))
model2.compile(loss = mae,optimizer = SGD(),metrics = ['mae'])
model.fit(x_2,y,epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 27ms/step - loss: 31.7795 - mae: 31.7795
Epoch 2/50
1/1 [==============================] - 0s 24ms/step - loss: 31.1522 - mae: 31.1522
Epoch 3/50
1/1 [==============================] - 0s 25ms/step - loss: 30.5248 - mae: 30.5248
Epoch 4/50
1/1 [==============================] - 0s 16ms/step - loss: 29.8975 - mae: 29.8975
Epoch 5/50
1/1 [==============================] - 0s 22ms/step - loss: 29.2701 - mae: 29.2701
Epoch 6/50
1/1 [==============================] - 0s 21ms/step - loss: 28.6428 - mae: 28.6428
Epoch 7/50
1/1 [==============================] - 0s 16ms/step - loss: 28.0154 - mae: 28.0154
Epoch 8/50
1/1 [==============================] - 0s 22ms/step - loss: 27.3881 - mae: 27.3881
Epoch 9/50
1/1 [==============================] - 0s 16ms/step - loss: 26.7607 - mae: 26.7607
Epoch 10/50
1/1 [==============================] - 0s 18ms/step - loss: 26.1334 - mae: 26.1334
Epoch 11/50
1/1 [==============================] - 0s 19ms/

In [ ]:
X = tf.constant(np.random.randint(low=10,high=100,size=100),dtype=float)
y =tf.constant(np.random.randint(low=1,high=10,size=100))
print(X,y) 

tf.Tensor(
[98. 36. 31. 32. 65. 46. 63. 69. 69. 70. 47. 89. 26. 11. 58. 40. 79. 82.
 86. 51. 12. 15. 45. 53. 99. 81. 97. 54. 18. 13. 77. 47. 65. 39. 17. 45.
 74. 15. 76. 90. 21. 55. 49. 85. 61. 37. 37. 80. 49. 90. 85. 40. 66. 93.
 21. 73. 94. 69. 91. 81. 21. 36. 16. 95. 52. 65. 20. 74. 60. 57. 82. 94.
 16. 25. 34. 76. 30. 19. 18. 51. 42. 80. 17. 80. 50. 37. 44. 89. 92. 58.
 56. 45. 26. 60. 58. 52. 99. 14. 74. 99.], shape=(100,), dtype=float32) tf.Tensor(
[6 1 3 7 5 9 5 3 2 7 9 6 4 3 9 6 6 9 6 7 4 6 2 1 6 6 8 9 3 6 6 3 8 5 6 8 4
 3 8 5 1 5 8 5 6 5 7 7 7 3 9 5 2 5 2 5 7 8 7 8 5 7 3 7 7 1 2 9 5 6 1 2 6 3
 1 3 5 2 4 2 5 8 8 1 1 3 7 6 4 1 4 1 2 5 2 9 5 9 2 6], shape=(100,), dtype=int64)


In [ ]:
x_train = X[:40]
x_val = X[40:80]
x_test = X[80:]
y_train = y[:40]
y_val = y[40:80]
y_test=  y[80:]

In [ ]:
model = Sequential()
model.add(Dense(100,name='dense1'))
model.add(Dense(20,name='dense2'))
model.add(Dense(1))
model.compile(loss=mae ,optimizer =SGD(),metrics = ['mae'] )
history = model.fit(tf.expand_dims(x_train,-1),y_train,epochs= 100,
                    validation_data = [tf.expand_dims(x_val,-1),y_val])

Epoch 1/100
2/2 [==============================] - 1s 196ms/step - loss: 37.4557 - mae: 37.4557 - val_loss: 3.9719 - val_mae: 3.9719
Epoch 2/100
2/2 [==============================] - 0s 36ms/step - loss: 4.3491 - mae: 4.3491 - val_loss: 2.2283 - val_mae: 2.2283
Epoch 3/100
2/2 [==============================] - 0s 33ms/step - loss: 2.3550 - mae: 2.3550 - val_loss: 2.2991 - val_mae: 2.2991
Epoch 4/100
2/2 [==============================] - 0s 35ms/step - loss: 2.4182 - mae: 2.4182 - val_loss: 2.6079 - val_mae: 2.6079
Epoch 5/100
2/2 [==============================] - 0s 39ms/step - loss: 3.0487 - mae: 3.0487 - val_loss: 4.2359 - val_mae: 4.2359
Epoch 6/100
2/2 [==============================] - 0s 49ms/step - loss: 4.6913 - mae: 4.6913 - val_loss: 2.3100 - val_mae: 2.3100
Epoch 7/100
2/2 [==============================] - 0s 33ms/step - loss: 2.3823 - mae: 2.3823 - val_loss: 3.7855 - val_mae: 3.7855
Epoch 8/100
2/2 [==============================] - 0s 79ms/step - loss: 3.9409 - mae: 3

In [ ]:
pred = model.predict(tf.expand_dims(x_test,-1))

1/1 [==============================] - 0s 319ms/step


In [ ]:
pred = model.predict(tf.expand_dims(x_test,-1))
mse_1 = tf.keras.losses.mse(y_test,tf.squeeze(pred)).numpy 
mae_1 = tf.keras.losses.mae(y_test,tf.squeeze(pred)).numpy 


In [ ]:
mode2 = Sequential()
mode2.add(Dense(10,name='dense1'))
mode2.add(Dense(20,name='dense2'))
mode2.add(Dense(1))
mode2.compile(loss=mae ,optimizer =SGD(),metrics = ['mae'] )
history = mode2.fit(tf.expand_dims(x_train,-1),y_train,epochs= 50,
                    validation_data = [tf.expand_dims(x_val,-1),y_val])
pred = mode2.predict(tf.expand_dims(x_test,-1))
mse_2 = tf.keras.losses.mse(y_test,tf.squeeze(pred)).numpy 
mae_2 = tf.keras.losses.mae(y_test,tf.squeeze(pred)).numpy 


Epoch 1/50
2/2 [==============================] - 1s 194ms/step - loss: 41.9615 - mae: 41.9615 - val_loss: 3.5545 - val_mae: 3.5545
Epoch 2/50
2/2 [==============================] - 0s 53ms/step - loss: 4.5410 - mae: 4.5410 - val_loss: 4.4177 - val_mae: 4.4177
Epoch 3/50
2/2 [==============================] - 0s 57ms/step - loss: 4.5603 - mae: 4.5603 - val_loss: 2.8105 - val_mae: 2.8105
Epoch 4/50
2/2 [==============================] - 0s 53ms/step - loss: 3.0757 - mae: 3.0757 - val_loss: 2.2232 - val_mae: 2.2232
Epoch 5/50
2/2 [==============================] - 0s 54ms/step - loss: 2.3563 - mae: 2.3563 - val_loss: 2.2501 - val_mae: 2.2501
Epoch 6/50
2/2 [==============================] - 0s 53ms/step - loss: 2.5822 - mae: 2.5822 - val_loss: 3.1712 - val_mae: 3.1712
Epoch 7/50
2/2 [==============================] - 0s 36ms/step - loss: 3.3324 - mae: 3.3324 - val_loss: 6.4360 - val_mae: 6.4360
Epoch 8/50
2/2 [==============================] - 0s 62ms/step - loss: 5.2697 - mae: 5.2697 - 

In [ ]:
mode3 = Sequential()
mode3.add(Dense(100,name='dense1'))
mode3.add(Dense(50,name='dense2'))
mode3.add(Dense(1))
mode3.compile(loss=mae ,optimizer =SGD(),metrics = ['mae'] )
history = mode3.fit(tf.expand_dims(x_train,-1),y_train,epochs= 150,
                    validation_data = [tf.expand_dims(x_val,-1),y_val])
pred = mode3.predict(tf.expand_dims(x_test,-1))
mse_3 = tf.keras.losses.mse(y_test,tf.squeeze(pred)).numpy 
mae_3 = tf.keras.losses.mae(y_test,tf.squeeze(pred)).numpy 


Epoch 1/150
2/2 [==============================] - 2s 582ms/step - loss: 2.6563 - mae: 2.6563 - val_loss: 147.3403 - val_mae: 147.3403
Epoch 2/150
2/2 [==============================] - 0s 77ms/step - loss: 111.4939 - mae: 111.4939 - val_loss: 7.8483 - val_mae: 7.8483
Epoch 3/150
2/2 [==============================] - 0s 168ms/step - loss: 6.1288 - mae: 6.1288 - val_loss: 2.3637 - val_mae: 2.3637
Epoch 4/150
2/2 [==============================] - 0s 193ms/step - loss: 2.9567 - mae: 2.9567 - val_loss: 2.5371 - val_mae: 2.5371
Epoch 5/150
2/2 [==============================] - 0s 76ms/step - loss: 2.9032 - mae: 2.9032 - val_loss: 2.2917 - val_mae: 2.2917
Epoch 6/150
2/2 [==============================] - 0s 141ms/step - loss: 2.6345 - mae: 2.6345 - val_loss: 2.8512 - val_mae: 2.8512
Epoch 7/150
2/2 [==============================] - 0s 156ms/step - loss: 3.0414 - mae: 3.0414 - val_loss: 2.3576 - val_mae: 2.3576
Epoch 8/150
2/2 [==============================] - 0s 75ms/step - loss: 2.506

In [ ]:
results = [['model1',mse_1(),mae_1()],
           ['mode2',mse_2(),mae_2()],
           ['mode3',mse_3(),mae_3()]]
df = pd.DataFrame(results,columns = ['models','mse','mae'])
df           

models        mse       mae
0  model1  11.075602  2.622655
1   mode2  18.917459  3.778662
2   mode3  10.621469  2.495216

#Saving our MOdel

In [ ]:
mode3.save('model3.h5')

#Load MOdel

In [ ]:
load_model3 = tf.keras.models.load_model('/content/model3.h5')

In [ ]:
load_model3.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense1 (Dense)              (None, 100)               200       
                                                                 
 dense2 (Dense)              (None, 50)                5050      
                                                                 
 dense_18 (Dense)            (None, 1)                 51        
                                                                 
Total params: 5,301
Trainable params: 5,301
Non-trainable params: 0
_________________________________________________________________


In [ ]:
df = pd.read_csv('insurance.csv')
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df1 = pd.get_dummies(df)

In [ ]:
df1.shape

(1338, 12)

In [ ]:
df1.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes', 'region_northeast', 'region_northwest',
       'region_southeast', 'region_southwest'],
      dtype='object')

In [ ]:
X = df1[['age', 'bmi', 'children', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes', 'region_northeast', 'region_northwest',
       'region_southeast', 'region_southwest']]
y = df1['charges']
x_train = X.iloc[:800,:]
y_train = y[:800]
x_test = X.iloc[800:,:]
y_test = y[800:]

In [ ]:
model = Sequential()
model.add(Dense(100,input_shape=(11,)))
#model.add(Dense(40))
model.add(Dense(1))
model.compile(loss= mae,optimizer=SGD(),metrics =['mae'])
history = model.fit(x_train,y_train,validation_data=[x_test,y_test],epochs=100)

Epoch 1/100
25/25 [==============================] - 2s 30ms/step - loss: 8528.3242 - mae: 8528.3242 - val_loss: 8901.6855 - val_mae: 8901.6855
Epoch 2/100
25/25 [==============================] - 0s 11ms/step - loss: 7423.8301 - mae: 7423.8301 - val_loss: 7571.6406 - val_mae: 7571.6406
Epoch 3/100
25/25 [==============================] - 0s 9ms/step - loss: 7626.6064 - mae: 7626.6064 - val_loss: 8238.0605 - val_mae: 8238.0605
Epoch 4/100
25/25 [==============================] - 0s 6ms/step - loss: 7512.5239 - mae: 7512.5239 - val_loss: 8808.8389 - val_mae: 8808.8389
Epoch 5/100
25/25 [==============================] - 0s 9ms/step - loss: 7340.0024 - mae: 7340.0024 - val_loss: 8333.6670 - val_mae: 8333.6670
Epoch 6/100
25/25 [==============================] - 0s 8ms/step - loss: 7508.1738 - mae: 7508.1738 - val_loss: 7198.6685 - val_mae: 7198.6685
Epoch 7/100
25/25 [==============================] - 0s 13ms/step - loss: 7191.6543 - mae: 7191.6543 - val_loss: 8254.6152 - val_mae: 8254.6

In [ ]:
pred = model.predict((x_test))
mse = tf.keras.losses.mse(y_test,tf.squeeze(pred)).numpy 
mae = tf.keras.losses.mae(y_test,tf.squeeze(pred)).numpy 


17/17 [==============================] - 0s 2ms/step


In [ ]:
model1 = Sequential()
model1.add(Dense(100))
model1.add(Dense(40))
model1.add(Dense(1))
model1.compile(loss= mae,optimizer=tf.keras.optimizers.SGD(),metrics =['mae'])
history = model1.fit(x_train,y_train,epochs=100,validation_data=(x_test,y_test))

Epoch 1/100
25/25 [==============================] - 1s 10ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 2/100
25/25 [==============================] - 0s 4ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 3/100
25/25 [==============================] - 0s 4ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 4/100
25/25 [==============================] - 0s 5ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 5/100
25/25 [==============================] - 0s 6ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 6/100
25/25 [==============================] - 0s 4ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 7/100
25/25 [==============================] - 0s 5ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 8/100
25/25 [==============================] - 0s 5ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 9/100
25/25 [============================

In [ ]:
pred = model.predict((x_test))
mse1 = tf.keras.losses.mse(y_test,tf.squeeze(pred)).numpy()
mae1 = tf.keras.losses.mae(y_test,tf.squeeze(pred)).numpy() 


17/17 [==============================] - 0s 2ms/step


#Scaling Data

In [ ]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import MinMaxScaler,OneHotEncoder
from sklearn.model_selection import train_test_split

# Create column transformer (this will help us normalize/preprocess our data)
ct = make_column_transformer(
    (MinMaxScaler(), ["age", "bmi", "children"]), # get all values between 0 and 1
    (OneHotEncoder(handle_unknown="ignore"), ["sex", "smoker", "region"])
)

# Create X & y
X = df.drop("charges", axis=1)
y = df["charges"]

# Build our train and test sets (use random state to ensure same split as before)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit column transformer on the training data only (doing so on test data would result in data leakage)
ct.fit(X_train)

# Transform training and test data with normalization (MinMaxScalar) and one hot encoding (OneHotEncoder)
X_train_normal = ct.transform(X_train)
X_test_normal = ct.transform(X_test)

In [ ]:
# Set random seed
tf.random.set_seed(42)

# Build the model (3 layers, 100, 10, 1 units)
insurance_model_3 = tf.keras.Sequential([
  tf.keras.layers.Dense(100),
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(1)
])

# Compile the model
insurance_model_3.compile(loss=tf.keras.losses.mae,
                          optimizer=tf.keras.optimizers.Adam(),
                          metrics=['mae'])

# Fit the model for 200 epochs (same as insurance_model_2)
insurance_model_3.fit(X_train_normal, y_train, epochs=50, verbose=0,validation_data=(X_test_normal,y_test)) 

In [ ]:
y_test

1231    20167.33603
768     14319.03100
847      2438.05520
510     11763.00090
363      2597.77900
           ...     
882      2585.85065
1039    22493.65964
874      8891.13950
757     23065.42070
701      9541.69555
Name: charges, Length: 268, dtype: float64

In [ ]:
model = Sequential()
model.add(Dense(100,input_shape=(11,)))
#model.add(Dense(40))
model.add(Dense(1))
model.compile(loss= mae,optimizer=SGD(),metrics =['mae'])
history = model.fit(x_train_cv,y_train,validation_data=(x_test_cv,y_test),epochs=100)

Epoch 1/100


ValueError: ignored